# This workflow will build a package using Maven and then publish it to GitHub docker registry
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Deploy to Production
env:
  NAMESPACE: production
  REPO: crimsy/crawler

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Publish to Docker Registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: Build Docker image
        run: docker build -t ${REPO}:${GITHUB_RUN_ID} -t ${REPO}:${NAMESPACE} .
      - name: Publish Docker image for run id
        run: docker push ${REPO}:${GITHUB_RUN_ID}
      - name: Publish Docker image for namespace
        run: docker push ${REPO}:${NAMESPACE}
  deploy:
    name: deploy to cluster
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: docker://nickgronow/kubectl
        with:
          config_data: ${{ secrets.KUBE_CONFIG }}
          args: set image --record cronjob/crawler crawler=${REPO}:${GITHUB_RUN_ID} -n ${NAMESPACE}

